commi 変数実装
s-takahashi-cin/GeekationJavaBasic pull request #3
Opened 2024-03-11 06:36 UTC by s-takahashi-cin

チェックお願いします！

2024-03-11 07:58 UTC, y0sh1ka2u requested changes

2024-03-11 07:58 UTC, y0sh1ka2u commented on src/basicSyntax/Variables.java
> +		System.out.println("私の好きな少数は"+num2+"です。");
`"私の好きな整数は" + num1 + "です。"`のように`+`の前後は半角スペース入れましょう！

2024-03-11 08:02 UTC, s-takahashi-cin commented on src/basicSyntax/Variables.java
> +		System.out.println("私の好きな少数は"+num2+"です。");
修正しました！よろしくお願いします！

2024-03-12 06:21 UTC, y0sh1ka2u approved these changes
OKです！

2024-03-12 06:40 UTC, merged